#!/bin/bash
if [[ $(id -u) -ne 0 ]]; then
    echo "You must run it as root" >&2
    exit 1
fi
BASH_DIR=$(cd $(dirname "${BASH_SOURCE[0]}");pwd)
cd $BASH_DIR
export BLUE='\033[1;94m'
export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'
USER=$(w|grep tty|grep -v grep|awk '{print $1}')
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u $USER)/bus"
KDE_SESSION=$(w|grep tty|grep plasma|grep -v grep|awk '{print $1}')
function torON_sys {
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
TOR_UID="tor"
TOR_PORT="9040"
TOR_DNSPort="5353"
check_ip="ident.me"
if [ "$(ping -4 -q -c1 -W0.5 google.com &>/dev/null && echo online || echo offline)" == "offline" ]
    then
        break
    else
        iptables-save > /tmp/iptables.conf
        mv -f /etc/tor/torrc /etc/tor/torrc.back
        cp -f src/sys.conf/torrc /etc/tor/torrc
        systemctl start tor
        while true
            do
                if ! [ -z $(torify curl -s $check_ip 2>/dev/null) ]
                    then
                        iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
                        iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10
                            do
                                iptables -t nat -A OUTPUT -d $NET -j RETURN
                        done
                        iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
                        iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
                        for NET in $TOR_EXCLUDE 127.0.0.0/8
                            do
                                iptables -A OUTPUT -d $NET -j ACCEPT
                        done
                        iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
                        iptables -A OUTPUT -j REJECT
                        clear
                        while true
                            do
                                runuser -u $TOR_UID nyx
                                break
                        done
                        clear
                        systemctl stop tor
                        mv -f /etc/tor/torrc.back /etc/tor/torrc
                        iptables -P INPUT ACCEPT
                        iptables -P FORWARD ACCEPT
                        iptables -P OUTPUT ACCEPT
                        iptables -t nat -F
                        iptables -t nat -X
                        iptables -t mangle -F
                        iptables -F
                        iptables -X
                        iptables-restore < /tmp/iptables.conf
                        rm -rf /tmp/iptables.conf
                    else
                        sleep 1
                        continue
                fi
                break
            done
fi
}

function nameON {
TOR_UID="tor"
NS=$(sed '6!d' src/sys.conf/variables.conf)
VETH=$(sed '7!d' src/sys.conf/variables.conf)
VPEER=$(sed '8!d' src/sys.conf/variables.conf)
VETH_ADDR=$(sed '9!d' src/sys.conf/variables.conf)
VPEER_ADDR=$(sed '10!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
if ! [ -z $KDE_SESSION ]
    then
        envi_vars="HOME=/home/$USER PULSE_SERVER=/run/user/$(id -u $USER)/pulse/native PULSE_COOKIE=/home/$USER/.config/pulse/cookie DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true XDG_RUNTIME_DIR=/run/user/$(id -u $USER) DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/namespace_dbus NO_AT_BRIDGE=1"
    else
        envi_vars="HOME=/home/$USER PULSE_SERVER=/run/user/$(id -u $USER)/pulse/native PULSE_COOKIE=/home/$USER/.config/pulse/cookie DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY XDG_RUNTIME_DIR=/run/user/$(id -u $USER) DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/namespace_dbus NO_AT_BRIDGE=1"
fi
ip netns add $NS
ip link add ${VETH} type veth peer name ${VPEER}
ip link set ${VPEER} netns $NS
ip addr add ${VETH_ADDR}/24 dev ${VETH}
ip link set ${VETH} up
ip netns exec $NS ip addr add ${VPEER_ADDR}/24 dev ${VPEER}
ip netns exec $NS ip link set ${VPEER} up
ip netns exec $NS ip link set lo up
ip netns exec $NS ip route add default via ${VETH_ADDR}
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s ${VPEER_ADDR}/24 -o $bad_tun -j MASQUERADE
iptables -A FORWARD -i $bad_tun -o ${VETH} -j ACCEPT
iptables -A FORWARD -o $bad_tun -i ${VETH} -j ACCEPT
ls /dev/pts/ | cat > /tmp/ttyold
runuser -u $USER xdg-dbus-proxy $DBUS_SESSION_BUS_ADDRESS /tmp/namespace_dbus &
xterm 2>/dev/null &
xterm 2>/dev/null &
xterm 2>/dev/null &
sleep 1
ls /dev/pts/ | cat > /tmp/ttynew
comm -3 /tmp/ttyold /tmp/ttynew|sed s/'\s'//g|cat > /tmp/tty
rm -rf /tmp/ttyold /tmp/ttynew
dns=$(sed '1!d' /tmp/tty)
namespace=$(sed '2!d' /tmp/tty)
tor_nyx=$(sed '3!d' /tmp/tty)
src/ttyecho -n /dev/pts/$tor_nyx "runuser -u $TOR_UID nyx"
src/ttyecho -n /dev/pts/$dns "ip netns exec $NS su - root"
src/ttyecho -n /dev/pts/$dns "clear ; dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml"
src/ttyecho -n /dev/pts/$namespace "ip netns exec $NS sudo -u $USER -i"
src/ttyecho -n /dev/pts/$namespace "export $envi_vars ; clear"
}

function nameOFF {
NS=$(sed '6!d' src/sys.conf/variables.conf)
VETH=$(sed '7!d' src/sys.conf/variables.conf)
VPEER=$(sed '8!d' src/sys.conf/variables.conf)
VETH_ADDR=$(sed '9!d' src/sys.conf/variables.conf)
VPEER_ADDR=$(sed '10!d' src/sys.conf/variables.conf)
ip netns exec $NS ip route del default via $VETH_ADDR
ip netns exec $NS ip addr del $VPEER_ADDR/24 dev $VPEER
ip netns exec $NS ip link set $VPEER down
ip netns exec $NS ip link set $VPEER netns 1
ip link set $VETH down
ip link del $VETH type veth peer name $VPEER
ip -4 addr flush label $VPEER
ip -4 addr flush label $VETH
ip netns exec $NS ip link set lo down
ip -all netns delete
sysctl -w net.ipv4.ip_forward=0
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -F
iptables -X
iptables-restore < /tmp/iptables.conf
rm -rf /tmp/tty /tmp/iptables.conf /tmp/namespace_dbus
}

function nameON_Wi-Fi {
TOR_UID="tor"
NS=$(sed '6!d' src/sys.conf/variables.conf)
VETH=$(sed '7!d' src/sys.conf/variables.conf)
VPEER=$(sed '8!d' src/sys.conf/variables.conf)
VETH_ADDR=$(sed '9!d' src/sys.conf/variables.conf)
VPEER_ADDR=$(sed '10!d' src/sys.conf/variables.conf)
wifi_iface=$(sed '11!d' src/sys.conf/variables.conf)
wifi_name=$(sed '12!d' src/sys.conf/variables.conf)
wifi_pass=$(sed '13!d' src/sys.conf/variables.conf)
wifi_reg=$(sed '14!d' src/sys.conf/variables.conf)
wifi_mac=$(sed '15!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
wifi_phy=$(cat /tmp/wifi_phy)
ip netns add $NS
ip link add ${VETH} type veth peer name ${VPEER}
ip link set ${VPEER} netns $NS
ip addr add ${VETH_ADDR}/24 dev ${VETH}
ip link set ${VETH} up
ip netns exec $NS ip addr add ${VPEER_ADDR}/24 dev ${VPEER}
ip netns exec $NS ip link set ${VPEER} up
ip netns exec $NS ip link set lo up
ip netns exec $NS ip route add default via ${VETH_ADDR}
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s ${VPEER_ADDR}/24 -o $bad_tun -j MASQUERADE
iptables -A FORWARD -i $bad_tun -o ${VETH} -j ACCEPT
iptables -A FORWARD -o $bad_tun -i ${VETH} -j ACCEPT
iw phy $wifi_phy set netns name $NS
ls /dev/pts/ | cat > /tmp/ttyold
xterm 2>/dev/null &
xterm 2>/dev/null &
xterm 2>/dev/null &
sleep 1
ls /dev/pts/ | cat > /tmp/ttynew
comm -3 /tmp/ttyold /tmp/ttynew|sed s/'\s'//g|cat > /tmp/tty
rm -rf /tmp/ttyold /tmp/ttynew
dns=$(sed '1!d' /tmp/tty)
hotspot=$(sed '2!d' /tmp/tty)
tor_nyx=$(sed '3!d' /tmp/tty)
src/ttyecho -n /dev/pts/$tor_nyx "runuser -u $TOR_UID nyx"
src/ttyecho -n /dev/pts/$dns "ip netns exec $NS su - root"
src/ttyecho -n /dev/pts/$dns "clear; dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml"
src/ttyecho -n /dev/pts/$hotspot "ip netns exec $NS su - root"
sleep 2
src/ttyecho -n /dev/pts/$hotspot "clear; $BASH_DIR/src/create_ap --daemon $wifi_iface $VPEER $wifi_name '$wifi_pass' --country $wifi_reg --mac $wifi_mac --no-virt ; while true; do $BASH_DIR/src/create_ap --list-clients $wifi_iface; sleep 2; clear; done"
}

function nameOFF_Wi-Fi {
NS=$(sed '6!d' src/sys.conf/variables.conf)
VETH=$(sed '7!d' src/sys.conf/variables.conf)
VPEER=$(sed '8!d' src/sys.conf/variables.conf)
VETH_ADDR=$(sed '9!d' src/sys.conf/variables.conf)
VPEER_ADDR=$(sed '10!d' src/sys.conf/variables.conf)
wifi_phy=$(cat /tmp/wifi_phy)
ip netns exec $NS iw phy $wifi_phy set netns 1
mv -f /etc/NetworkManager/NetworkManager.old /etc/NetworkManager/NetworkManager.conf
pkill -HUP NetworkManager
ip netns exec $NS ip route del default via $VETH_ADDR
ip netns exec $NS ip addr del $VPEER_ADDR/24 dev $VPEER
ip netns exec $NS ip link set $VPEER down
ip netns exec $NS ip link set $VPEER netns 1
ip link set $VETH down
ip link del $VETH type veth peer name $VPEER
ip -4 addr flush label $VPEER
ip -4 addr flush label $VETH
ip netns exec $NS ip link set lo down
ip -all netns delete
sysctl -w net.ipv4.ip_forward=0
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -F
iptables -X
iptables-restore < /tmp/iptables.conf
rm -rf /tmp/tty /tmp/iptables.conf /tmp/wifi_phy /tmp/create_ap.*.lock
}

function torOFF_name {
clear
ip route del 10.8.0.1/32 via 10.8.3.17
ip addr del dev $bad_tun local 10.8.3.18 peer 10.8.3.17
ip -4 addr flush label $bad_tun
ip tuntap del dev $bad_tun mode tun
systemctl stop tor
mv -f /etc/tor/torrc.back /etc/tor/torrc
pkill -15 xdg-dbus-proxy
nameOFF
}

function torON_name {
local_ip=$(sed '2!d' src/sys.conf/variables.conf)
local_port=$(sed '3!d' src/sys.conf/variables.conf)
bind_iface=$(sed '4!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
id="$RANDOM"
check_ip="ident.me"
socks_server="$local_ip:$local_port"
if [ "$(ping -4 -q -c1 -W0.5 google.com &>/dev/null && echo online || echo offline)" == "offline" ]
    then
        break
    else
        iptables-save > /tmp/iptables.conf
        mv -f /etc/tor/torrc /etc/tor/torrc.back
        cp -f src/sys.conf/torrc /etc/tor/torrc
        systemctl start tor
        while true
            do
                if ! [ -z $(torify curl -s $check_ip 2>/dev/null) ]
                    then
                        ip tuntap add dev $bad_tun mode tun
                        ip link set $bad_tun up
                        ip link set dev $bad_tun up mtu 1500
                        ip addr add 10.0.1.1/30 dev $bad_tun
                        ip addr add dev $bad_tun local 10.8.3.18 peer 10.8.3.17
                        ip route add 10.8.0.1/32 via 10.8.3.17
                        sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
                        ip rule add fwmark $id lookup $id
                        ip route add default via 10.0.1.2 table $id
                        iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id
                        nameON
                        clear
                        while true
                            do
                                src/badvpn --tundev $bad_tun --netif-ipaddr 10.0.1.2 --netif-netmask 255.255.255.0 --socks-server-addr $socks_server
                                break
                        done
                        torOFF_name
                    else
                        sleep 1
                        continue
                fi
                break
            done
fi
}

function torON_name_sys {
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
TOR_UID="tor"
TOR_PORT="9040"
TOR_DNSPort="5353"
local_ip=$(sed '2!d' src/sys.conf/variables.conf)
local_port=$(sed '3!d' src/sys.conf/variables.conf)
bind_iface=$(sed '4!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
id="$RANDOM"
check_ip="ident.me"
socks_server="$local_ip:$local_port"
if [ "$(ping -4 -q -c1 -W0.5 google.com &>/dev/null && echo online || echo offline)" == "offline" ]
    then
        break
    else
        iptables-save > /tmp/iptables.conf
        mv -f /etc/tor/torrc /etc/tor/torrc.back
        cp -f src/sys.conf/torrc /etc/tor/torrc
        systemctl start tor
        while true
            do
                if ! [ -z $(torify curl -s $check_ip 2>/dev/null) ]
                    then
                        iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
                        iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10
                            do
                                iptables -t nat -A OUTPUT -d $NET -j RETURN
                        done
                        iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
                        iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
                        for NET in $TOR_EXCLUDE 127.0.0.0/8
                            do
                                iptables -A OUTPUT -d $NET -j ACCEPT
                        done
                        iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
                        iptables -A OUTPUT -j REJECT
                        ip tuntap add dev $bad_tun mode tun
                        ip link set $bad_tun up
                        ip link set dev $bad_tun up mtu 1500
                        ip addr add 10.0.0.1/30 dev $bad_tun
                        ip addr add dev $bad_tun local 10.9.3.18 peer 10.9.3.17
                        ip route add 10.9.0.1/32 via 10.9.3.17
                        sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
                        ip rule add fwmark $id lookup $id
                        ip route add default via 10.0.0.2 table $id
                        iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id
                        nameON
                        clear
                        while true
                            do
                                src/badvpn --tundev $bad_tun --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr $socks_server
                                break
                        done
                        torOFF_name
                    else
                        sleep 1
                        continue
                fi
                break
            done
fi
}

function torOFF_name_wifi {
clear
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
ip route del 10.9.0.1/32 via 10.9.3.17
ip addr del dev $bad_tun local 10.9.3.18 peer 10.9.3.17
ip -4 addr flush label $bad_tun
ip tuntap del dev $bad_tun mode tun
systemctl stop tor
mv -f /etc/tor/torrc.back /etc/tor/torrc
nameOFF_Wi-Fi
}

function torON_name_wifi {
local_ip=$(sed '2!d' src/sys.conf/variables.conf)
local_port=$(sed '3!d' src/sys.conf/variables.conf)
bind_iface=$(sed '4!d' src/sys.conf/variables.conf)
wifi_iface=$(sed '11!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
id="$RANDOM"
socks_server="$local_ip:$local_port"
check_ip="ident.me"
if [ "$(ping -4 -q -c1 -W0.5 google.com &>/dev/null && echo online || echo offline)" == "offline" ]
    then
        break
    else
        cat /sys/class/net/$wifi_iface/phy80211/name > /tmp/wifi_phy
        iptables-save > /tmp/iptables.conf
        cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.old
        sed -i 15c\unmanaged-devices=interface-name:$wifi_iface src/sys.conf/NetworkManager.conf
        cp src/sys.conf/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf
        pkill -HUP NetworkManager
        mv -f /etc/tor/torrc /etc/tor/torrc.back
        cp -f src/sys.conf/torrc /etc/tor/torrc
        systemctl start tor
        while true
            do
                if ! [ -z $(torify curl -s $check_ip 2>/dev/null) ]
                    then
                        ip tuntap add dev $bad_tun mode tun
                        ip link set $bad_tun up
                        ip link set dev $bad_tun up mtu 1500
                        ip addr add 10.0.0.1/30 dev $bad_tun
                        ip addr add dev $bad_tun local 10.9.3.18 peer 10.9.3.17
                        ip route add 10.9.0.1/32 via 10.9.3.17
                        sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
                        ip rule add fwmark $id lookup $id
                        ip route add default via 10.0.0.2 table $id
                        iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id
                        nameON_Wi-Fi
                        clear
                        while true
                            do
                                src/badvpn --tundev $bad_tun --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr $socks_server
                                pkill -15 create_ap
                                break
                        done
                        torOFF_name_wifi
                    else
                        sleep 1
                        continue
                fi
                break
            done
fi
}

function torON_name_sys_wifi {
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
TOR_UID="tor"
TOR_PORT="9040"
TOR_DNSPort="5353"
local_ip=$(sed '2!d' src/sys.conf/variables.conf)
local_port=$(sed '3!d' src/sys.conf/variables.conf)
bind_iface=$(sed '4!d' src/sys.conf/variables.conf)
wifi_iface=$(sed '11!d' src/sys.conf/variables.conf)
bad_tun=$(sed '5!d' src/sys.conf/variables.conf)
id="$RANDOM"
socks_server="$local_ip:$local_port"
check_ip="ident.me"
if [ "$(ping -4 -q -c1 -W0.5 google.com &>/dev/null && echo online || echo offline)" == "offline" ]
    then
        break
    else
        cat /sys/class/net/$wifi_iface/phy80211/name > /tmp/wifi_phy
        iptables-save > /tmp/iptables.conf
        cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.old
        sed -i 15c\unmanaged-devices=interface-name:$wifi_iface src/sys.conf/NetworkManager.conf
        cp src/sys.conf/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf
        pkill -HUP NetworkManager
        mv -f /etc/tor/torrc /etc/tor/torrc.back
        cp -f src/sys.conf/torrc /etc/tor/torrc
        systemctl start tor
        while true
            do
                if ! [ -z $(torify curl -s $check_ip 2>/dev/null) ]
                    then
                        iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
                        iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
                        iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
                        for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10
                            do
                                iptables -t nat -A OUTPUT -d $NET -j RETURN
                        done
                        iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
                        iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
                        iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
                        for NET in $TOR_EXCLUDE 127.0.0.0/8
                            do
                                iptables -A OUTPUT -d $NET -j ACCEPT
                        done
                        iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
                        iptables -A OUTPUT -j REJECT
                        ip tuntap add dev $bad_tun mode tun
                        ip link set $bad_tun up
                        ip link set dev $bad_tun up mtu 1500
                        ip addr add 10.0.0.1/30 dev $bad_tun
                        ip addr add dev $bad_tun local 10.9.3.18 peer 10.9.3.17
                        ip route add 10.9.0.1/32 via 10.9.3.17
                        sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
                        ip rule add fwmark $id lookup $id
                        ip route add default via 10.0.0.2 table $id
                        iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id
                        nameON_Wi-Fi
                        clear
                        while true
                            do
                                src/badvpn --tundev $bad_tun --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr $socks_server
                                pkill -15 create_ap
                                break
                        done
                        torOFF_name_wifi
                    else
                        sleep 1
                        continue
                fi
                break
            done
fi
}

function settings {
     
    function install_dependency {
    pacman -Sy tor torsocks nyx bash util-linux procps hostapd iproute2 iw haveged dnsmasq iptables net-tools git xterm base-devel --noconfirm
    su - $USER -c "cd /tmp/ ; rm -rf yay ; git clone https://aur.archlinux.org/yay.git ; cd yay ; makepkg -si --noconfirm ; cd .. ; rm -rf yay"
    su - $USER -c "yay -Sy dnscrypt-proxy --noconfirm"
    cp -rf src/sys.conf/dnscrypt-proxy.toml /etc/dnscrypt-proxy/ ; cp -rf src/sys.conf/dnscrypt-proxy.service /etc/systemd/system/
    systemctl daemon-reload
    chattr -i /etc/resolv.conf
    systemctl --now disable systemd-resolved
    systemctl mask systemd-resolved
    pacman -Rsn resolvconf --noconfirm
    mv -f /etc/resolv.conf /etc/resolv.conf.back
    cp -rf src/sys.conf/resolv.conf /etc/
    chattr +i /etc/resolv.conf
    systemctl --now enable dnscrypt-proxy
    usermod -a -G tor ${USER}
    mv -f /etc/tor/torrc /etc/tor/torrc.old ; mv -f /etc/tor/torsocks.conf /etc/tor/torsocks.conf.old
    cp -rf src/sys.conf/torrc /etc/tor/ ; cp -rf src/sys.conf/torsocks.conf /etc/tor/torsocks.conf
    cp -rf src/sys.conf/tor.service /usr/lib/systemd/system/tor.service
    touch /var/lib/tor/control_socket ; touch /var/lib/tor/control_auth_cookie
    chown -R tor:tor /etc/tor/
    chown -R tor:tor /var/lib/tor
    chmod -R 750 /var/lib/tor
    systemctl daemon-reload
    clear
    while true
        do
            clear
            read -p "Install tor2tun in system (y/n) > " install_tor2tun
            case $install_tor2tun in
                [Yy] )  rm -rf /opt/tor2tun
                        mv -f $BASH_DIR /opt/
                        chown -R root:root /opt/tor2tun
                        echo -en '#!/bin/bash\n/opt/tor2tun/tor2tun' | su -c 'cat > /bin/tor2tun'
                        chmod +x /bin/tor2tun
                        clear
                        echo -e -n "$RED TOR2TUN INSTALLED"
                        sleep 3; clear; echo -e $RESETCOLOR; kill -15 $BASHPID ;;  
                [Nn] )  echo -e -n "  \n"
                        echo -e -n "$RED All Done \n"
                        sleep 1; return 1 ;;
            esac
    done
    }

    function configure_all {
    while true; do
    read -p "Enter localhost IP (127.0.0.1) > " local_ip
        if ! [ -z $local_ip ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter Tor local port (9050) > " local_port
        if ! [ -z $local_port ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter bind interface (veth1) > " bind_iface
        if ! [ -z $bind_iface ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter badvpn interface (tun11658) > " bad_tun
        if ! [ -z $bad_tun ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter name of namespace (ns1) > " NS
        if ! [ -z $NS ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter name of namespace link interface (veth1) > " VETH
        if ! [ -z $VETH ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter name of interface in namespace (peth0) > " VPEER
        if ! [ -z $VPEER ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter namespace link interface IP (10.200.1.1) > " VETH_ADDR
        if ! [ -z $VETH_ADDR ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter interface in namespace IP (10.200.1.2) > " VPEER_ADDR
        if ! [ -z $VPEER_ADDR ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter name of Wi-Fi interface (wlan1) > " wifi_iface
        if ! [ -z $wifi_iface ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter hotspot name (HotSpot) > " wifi_name
        if ! [ -z $wifi_name ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter hotspot password (minimum 8 characters) > " wifi_pass
        if ! [ -z $wifi_pass ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter hotspot region (BZ) > " wifi_reg
        if ! [ -z $wifi_reg ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done

    while true; do
    read -p "Enter hotspot MAC (46:03:08:01:89:55) > " wifi_mac
        if ! [ -z $wifi_mac ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    
cat <<EOF > src/sys.conf/variables.conf
This Is configuration file DON'T REMOVE IT
$local_ip
$local_port
$bind_iface
$bad_tun
$NS
$VETH
$VPEER
$VETH_ADDR
$VPEER_ADDR
$wifi_iface
$wifi_name
$wifi_pass
$wifi_reg
$wifi_mac
EOF
    }
    
    function configure_wifi {
    while true; do
    read -p "Enter name of Wi-Fi interface (wlan1) > " wifi_iface
        if ! [ -z $wifi_iface ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    
    while true; do
    read -p "Enter hotspot name (HotSpot) > " wifi_name
        if ! [ -z $wifi_name ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    
    while true; do
    read -p "Enter hotspot password (minimum 8 characters) > " wifi_pass
        if ! [ -z $wifi_pass ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    
    while true; do
    read -p "Enter hotspot region (BZ) > " wifi_reg
        if ! [ -z $wifi_reg ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    
    while true; do
    read -p "Enter hotspot MAC (46:03:08:01:89:55) > " wifi_mac
        if ! [ -z $wifi_mac ];
            then
                clear
                break
            else
                clear
                continue
        fi
    done
    sed -i "11c\\$wifi_iface" src/sys.conf/variables.conf
    sed -i "12c\\$wifi_name" src/sys.conf/variables.conf
    sed -i "13c\\$wifi_pass" src/sys.conf/variables.conf
    sed -i "14c\\$wifi_reg" src/sys.conf/variables.conf
    sed -i "15c\\$wifi_mac" src/sys.conf/variables.conf
    }
    
settings_options=("Install dependency" "Configure all" "Configure only Wi-Fi" "Go Back")

    function set_opt_menu {
    echo -en "$RED      Settings \n"
    for i in $(seq 0 $((${#settings_options[@]}-1)))
        do
            echo "$((i+1)))" "${settings_options[$i]}"
    done
    }

set_prompt=$(clear; set_opt_menu; echo -e -n " \n \n")
PS3="${set_prompt}Select option [1-${#settings_options[@]}] : "
select set_opt in "${settings_options[@]}"; do 
    case "$REPLY" in

    1 ) clear
        install_dependency
        continue;;
    2 ) clear
        configure_all
        continue;;
    3 ) clear
        configure_wifi
        continue;;

    ${#settings_options[@]} ) clear; echo -e $RESETCOLOR; break;;
    *) echo -e -n "  \n"; echo -e -n  "${BLUE}Invalid option. Try another one. \n"; sleep 0.5 ;continue;;

    esac
done
}

options=("Tor->System" "Tor->namespace" "Tor->System->namespace" "Tor->namespace->Wi-Fi" "Tor->System->namespace->Wi-Fi" "Settings" "Quit")

function opt_menu {
echo -en "$RED          TOR2TUN \n"
for i in $(seq 0 $((${#options[@]}-1)))
    do
        echo "$((i+1)))" "${options[$i]}"
done
}

prompt=$(clear; opt_menu; echo -e -n " \n \n")
PS3="${prompt}Select option [1-${#options[@]}] : "
select opt in "${options[@]}"; do 
    case "$REPLY" in

    1 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Run Tor->System \n"
        torON_sys
        mv -f ~/.bash_history.back ~/.bash_history
        continue;;
    2 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Run Tor->namespace \n"
        torON_name
        mv -f ~/.bash_history.back ~/.bash_history
        continue;;
    3 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Run Tor->System->namespace \n"
        torON_name_sys
        mv -f ~/.bash_history.back ~/.bash_history
        continue;;
    4 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Run Tor->namespace->Wi-Fi \n"
        torON_name_wifi
        mv -f ~/.bash_history.back ~/.bash_history
        continue;;
    5 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Run Tor->System->namespace->Wi-Fi \n"
        torON_name_sys_wifi
        mv -f ~/.bash_history.back ~/.bash_history
        continue;;
    6 ) clear
        cp -f ~/.bash_history ~/.bash_history.back
        echo -e -n "$BLUE Settings \n"
        settings
        mv -f ~/.bash_history.back ~/.bash_history
        PS3="${prompt}Select option [1-${#options[@]}] : "
        continue;;

    ${#options[@]} ) clear; echo -e $RESETCOLOR; break;;
    *) echo -e -n "  \n"; echo -e -n  "${BLUE}Invalid option. Try another one. \n"; sleep 0.5 ;continue;;

    esac
done
