#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
export BLUE='\033[1;94m'
export RED='\033[1;91m'

title="$RED 		Hi BRO!) it's tor2tun \n"
prompt=
options=("Tor->System" "Tor->namespace" "Tor->System->namespace" "Tor->namespace->Wi-Fi" "Tor->System->namespace->Wi-Fi" "Settings")

clear
echo -e -n  "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in

	1 ) clear
		echo -e -n "$BLUE Tor->System \n"
		src/torON_sys
		clear
		src/torOFF_sys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	2 ) clear
		echo -e -n "$BLUE Tor->namespace \n"
		src/torON_name
		clear
		src/torOFF_name
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	3 ) clear
		echo -e -n "$BLUE Tor->System->namespace \n"
		src/torON_name_sys
		clear
		src/torOFF_name
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	4 ) clear
		echo -e -n "$BLUE Run Tor->namespace->Wi-Fi \n"
		src/torON_name_wifi
		clear
		src/torOFF_name_wifi
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	5 ) clear
		echo -e -n "$BLUE Tor->System->namespace->Wi-Fi \n"
		src/torON_name_sys_wifi
		clear
		src/torOFF_name_wifi
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    6 ) clear
		echo -e -n "$BLUE Settings \n"
		src/settings
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;

    $(( ${#options[@]}+1 )) ) clear; break;;
    *) echo -e -n  "$RED Invalid option. Try another one. \n";continue;;

    esac

done
