#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
echo "This Is configuration file DON'T REMOVE IT" | cat > variables.conf

read -p "Enter localhost IP (127.0.0.1) > " local_ip
echo $local_ip | cat >> variables.conf

read -p "Enter Tor local port (9050) > " local_port
echo $local_port | cat >> variables.conf

read -p "Enter bind interface (veth1) > " bind_iface
echo $bind_iface | cat >> variables.conf

read -p "Enter badvpn interface (tun11658) > " bad_tun
echo $bad_tun | cat >> variables.conf

read -p "Enter name of namespace (ns1) > " NS
echo $NS | cat >> variables.conf

read -p "Enter name of namespace link interface (veth1) > " VETH
echo $VETH | cat >> variables.conf

read -p "Enter name of interface in namespace (peth0) > " VPEER
echo $VPEER | cat >> variables.conf

read -p "Enter namespace link interface IP (10.200.1.1) > " VETH_ADDR
echo $VETH_ADDR | cat >> variables.conf

read -p "Enter interface in namespace IP (10.200.1.2) > " VPEER_ADDR
echo $VPEER_ADDR | cat >> variables.conf

read -p "Enter name of Wi-Fi interface (wlan1) > " wifi_iface
echo $wifi_iface | cat >> variables.conf

read -p "Enter hotspot name (HotSpot) > " wifi_name
echo $wifi_name | cat >> variables.conf

read -p "Enter hotspot password (minimum 8 characters) > " wifi_pass
echo $wifi_pass | cat >> variables.conf

read -p "Enter hotspot region (BZ) > " wifi_reg
echo $wifi_reg | cat >> variables.conf

read -p "Enter hotspot MAC (46:03:08:01:89:55) > " wifi_mac
echo $wifi_mac | cat >> variables.conf
