#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

VPEER=$(sed '8!d' variables.conf)
wifi_iface=$(sed '11!d' variables.conf)
wifi_name=$(sed '12!d' variables.conf)
wifi_pass=$(sed '13!d' variables.conf)
wifi_reg=$(sed '14!d' variables.conf)
wifi_mac=$(sed '15!d' variables.conf)


sudo ./create_ap $wifi_iface $VPEER $wifi_name $wifi_pass --country $wifi_reg --mac $wifi_mac --no-virt
