#!/bin/bash

set -x

NS=$(sed '6!d' variables.conf)
VETH=$(sed '7!d' variables.conf)
VPEER=$(sed '8!d' variables.conf)
VETH_ADDR=$(sed '9!d' variables.conf)
VPEER_ADDR=$(sed '10!d' variables.conf)
bad_tun=$(sed '5!d' variables.conf)

dist=$(cat /tmp/dist)
wifi_phy=$(cat /tmp/wifi_phy)
# Create namespace
sudo ip netns add $NS

# Create veth link.
sudo ip link add ${VETH} type veth peer name ${VPEER}

# Add peer-1 to NS.
sudo ip link set ${VPEER} netns $NS

# Setup IP address of ${VETH}.
sudo ip addr add ${VETH_ADDR}/24 dev ${VETH}
sudo ip link set ${VETH} up

# Setup IP ${VPEER}.
sudo ip netns exec $NS ip addr add ${VPEER_ADDR}/24 dev ${VPEER}
sudo ip netns exec $NS ip link set ${VPEER} up
sudo ip netns exec $NS ip link set lo up
sudo ip netns exec $NS ip route add default via ${VETH_ADDR}

# Enable IP-forwarding.
sudo sysctl -w net.ipv4.ip_forward=1

# Enable masquerading of 10.200.1.0.
sudo iptables -t nat -A POSTROUTING -s ${VPEER_ADDR}/24 -o $bad_tun -j MASQUERADE
 
sudo iptables -A FORWARD -i $bad_tun -o ${VETH} -j ACCEPT
sudo iptables -A FORWARD -o $bad_tun -i ${VETH} -j ACCEPT

# Add Wi-Fi iface to namespace
sudo iw phy $wifi_phy set netns name $NS

ls /dev/pts/ | cat > /tmp/ttyold && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && ls /dev/pts/ | cat > /tmp/ttynew && grep -vf /tmp/ttyold /tmp/ttynew | sort -u > /tmp/tty
dns=$(sed '1!d' /tmp/tty)
hotspot=$(sed '2!d' /tmp/tty)
tor_nyx=$(sed '3!d' /tmp/tty)
sudo ./ttyecho -n /dev/pts/$tor_nyx "sudo nyx"
sudo ./ttyecho -n /dev/pts/$dns "sudo ip netns exec $NS sudo -u $USER -i"
sudo ./ttyecho -n /dev/pts/$hotspot "sudo ip netns exec $NS sudo -u $USER -i"
sudo ./ttyecho -n /dev/pts/$dns sudo dnscrypt-proxy
sleep 2
sudo ./ttyecho -n /dev/pts/$hotspot $dist/HotSpotON
