#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
export BLUE='\033[1;94m'
export RED='\033[1;91m'

title="$RED 		WoW it's Settings \n"
prompt=
options=("Fix SUDO passwordless" "Install dependency" "Configure all" "Configure only Wi-Fi")

clear
echo -e -n  "$title"
PS3="$prompt "
select opt in "${options[@]}" "Go Back"; do 

    case "$REPLY" in

	1 ) clear
		echo -e -n "$BLUE Fix SUDO passwordless \n"
		./fix_sudo 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    2 ) clear
		echo -e -n "$BLUE Installing dependency \n"
		./dependency_installer 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    3 ) clear
		echo -e -n "$BLUE Configure all \n"
		./configure_all 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    4 ) clear
		echo -e -n "$BLUE Configure only Wi-Fi \n"
		./configure_wifi 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;

    $(( ${#options[@]}+1 )) ) clear; break;;
    *) echo -e -n  "$RED Invalid option. Try another one. \n";continue;;

    esac

done
