#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
TOR_UID="debian-tor"
TOR_PORT="9040"
TOR_DNSPort="5353"
sudo iptables-save > /tmp/iptables.conf
sudo mv -f /etc/tor/torrc /etc/tor/torrc.back
sudo cp -f ./torrc /etc/tor/torrc
sudo service tor start
sleep 5
sudo iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
sudo iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
sudo iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
sudo iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNSPort
sudo iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
sudo iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
sudo iptables -t nat -A OUTPUT -d $NET -j RETURN
done
sudo iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
sudo iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
sudo iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
sudo iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
for NET in $TOR_EXCLUDE 127.0.0.0/8; do
sudo iptables -A OUTPUT -d $NET -j ACCEPT
done
sudo iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
sudo iptables -A OUTPUT -j REJECT
clear
sudo nyx
