#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x
sudo service tor stop
sudo mv -f /etc/tor/torrc.back /etc/tor/torrc
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -F
sudo iptables -X
sudo iptables-restore < /tmp/iptables.conf
rm -r /tmp/dist /tmp/iptables.conf
