#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

local_ip=$(sed '2!d' variables.conf)
local_port=$(sed '3!d' variables.conf)
bind_iface=$(sed '4!d' variables.conf)
bad_tun=$(sed '5!d' variables.conf)


id="$RANDOM"
socks_server="$local_ip:$local_port"
pwd | cat > /tmp/dist
dist=$(cat /tmp/dist)
sudo iptables-save > /tmp/iptables.conf
sudo mv -f /etc/tor/torrc /etc/tor/torrc.back
sudo cp -f ./torrc /etc/tor/torrc
sudo service tor start
sleep 5
sudo ip tuntap add dev $bad_tun mode tun
sudo ip link set $bad_tun up
sudo ip link set dev $bad_tun up mtu 1500
sudo ip addr add 10.0.0.1/30 dev $bad_tun
sudo ip addr add dev $bad_tun local 10.9.3.18 peer 10.9.3.17
sudo ip route add 10.9.0.1/32 via 10.9.3.17
sudo sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
sudo ip rule add fwmark $id lookup $id
sudo ip route add default via 10.0.0.2 table $id
sudo iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id

xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --hide-borders --working-directory=$dist -e "./nameON"

sudo ./badvpn-tun2socks --tundev $bad_tun --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr $socks_server
